<<<<<<< HEAD
# handlers/main.yml

=======
# Handlers pour le rôle
>>>>>>> b19ef85 (Ajout du rôle Ansible Wordpress complet)
- name: restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
<<<<<<< HEAD
  listen: "restart apache2" # This handler listens for "restart apache2"
  when: ansible_os_family == "Debian"

- name: restart httpd_shell
  ansible.builtin.shell: |
    pkill -f "/usr/sbin/httpd" || true # Stop current httpd process (true to prevent failure if not running)
    /usr/sbin/httpd -DFOREGROUND &    # Restart httpd in foreground for container
  args:
    executable: /bin/bash
  listen: "restart httpd_shell" # This handler listens for "restart httpd_shell"
  when: ansible_os_family == "RedHat"
=======
  when: ansible_os_family == 'Debian'

- name: restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: ansible_os_family == 'RedHat'
>>>>>>> b19ef85 (Ajout du rôle Ansible Wordpress complet)
